print("---------------------")
print("COMPROBANTE DE PAGO")
print("---------------------")
print("Cliente: Joaquín Roman Vázquez Zúñiga")
print("Servicio: Crossup")
print("Plan: Mensual")
print("---------------------")
print("Subtotal = $149 pesos")
print("IVA 16%= $23.84")
print("TOTAL= $172.84")
print("---------------------")
print("Gracias por su prerencia")
print("---------------------")
